app:
  name: service-subs
  version: "0.1.0"

http:
  host: localhost
  port: 8080

postgresql:
  name: webdb
  user: user
  password: password
  host: postgres
  port: 5432
  
logs:
  loglevel: -4

# slog.LevelError = 8
# slog.LevelWarn = 4
# slog.LevelInfo = 0
# slog.LevelDebug = -4
